const {chromium}=require('C:/Users/YiLight/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const path=require('path');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'msedge'});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 let configured=false;await page.route('**/api/status',r=>r.fulfill({json:{configured,maxPdfBytes:200*1024*1024}}));
 await page.goto('http://127.0.0.1:8765');await page.waitForSelector('#connection:has-text("未配置")');
 if((await page.locator('#question').getAttribute('placeholder'))?.trim())throw Error('Question input should not show an example prompt');
 await page.screenshot({path:path.join(__dirname,'welcome.png')});
 const bytes=Array.from(require('fs').readFileSync(path.join(__dirname,'fixture.pdf')));
 const transfer=await page.evaluateHandle(bytes=>{const dt=new DataTransfer();dt.items.add(new File([new Uint8Array(bytes)],'fixture.pdf',{type:'application/pdf'}));return dt;},bytes);
 await page.locator('body').dispatchEvent('dragenter',{dataTransfer:transfer});
 if(!await page.locator('body.file-drag').count())throw Error('Missing drag overlay');
 await page.locator('body').dispatchEvent('drop',{dataTransfer:transfer});
 if(await page.locator('body.file-drag').count())throw Error('Drag overlay not cleared');
 await page.waitForSelector('.pdf-page');
 if(await page.locator('#relevanceThreshold').inputValue()!=='50')throw Error('Default salience threshold should be 50%');
 if((await page.locator('#timing').textContent()).trim())throw Error('Upload duration should not be displayed');
 const figure=await page.evaluate(()=>{const f=eval('doc.figures[0]');return {id:f.captionId,pid:f.captionId};});
 const inputHeights=await page.evaluate(()=>[document.querySelector('#question').getBoundingClientRect().height,document.querySelector('#askButton').getBoundingClientRect().height]);
 if(Math.abs(inputHeights[0]-inputHeights[1])>1)throw Error('Question input and send button are not aligned');
 await page.locator('#columnCount').selectOption('2');
 const columns=await page.locator('#pages').evaluate(el=>getComputedStyle(el).gridTemplateColumns.split(' ').length);if(columns!==2)throw Error('Two-column view failed');
 await page.locator('#zoomIn').click();if(await page.locator('#zoomValue').textContent()!=='110%')throw Error('Zoom failed');
 if(await page.locator('#resultSort').inputValue()!=='document')throw Error('Document order should be the default sort');
 await page.locator('#question').fill('How was the experiment designed?');await page.locator('#question').press('Enter');
 if(!await page.locator('#error').isVisible())throw Error('Missing key gate failed');
 await page.route('**/api/key',r=>{configured=true;return r.fulfill({json:{configured:true}});});
 await page.locator('#apiKey').fill('mock-test-key-not-sent');await page.locator('#keyForm button').click();
 await page.route('**/api/score',async r=>{await new Promise(resolve=>setTimeout(resolve,50));const q=r.request().postDataJSON();const scores={};q.ids.forEach((id,i)=>scores[id]=id===figure.id||id===figure.pid?3:id.startsWith('p')?2.8:[3,2,1,0][i%4]);await r.fulfill({json:{scores,elapsedMs:25,usage:{},model:'mock-for-ui-test'}});});
 await page.locator('#askButton').click();await page.waitForSelector('#askButton[aria-label="暂停分析"]');
 if(await page.locator('#question').inputValue()!=='')throw Error('Question input was not cleared after sending');
 const pauseSize=await page.locator('#askButton').evaluate(el=>parseFloat(getComputedStyle(el,'::before').height));if(pauseSize>14)throw Error('Pause icon is too large');
 if(await page.getByText('停止',{exact:true}).count())throw Error('Text stop control should not exist');
 await page.waitForSelector('#progressText:has-text("全文评分完成")');await page.waitForSelector('#askButton[aria-label="定位原文"]');
 if(!/^Jev 处理 \d+\.\d{2} 秒$/.test((await page.locator('#timing').textContent()).trim()))throw Error('Jev processing duration is missing');
 await page.waitForSelector('.mark.focused');
 const all=await page.locator('.mark').count();if(!all)throw Error('No highlights');
 if(await page.locator('.result-item').count()>8)throw Error('Evidence selection is not selective');
 if(!/相对显著度 \d+%/.test(await page.locator('.result-item .level').first().textContent()))throw Error('Relative salience is missing');
 const defaultResults=await page.locator('.result-item').count();await page.locator('#relevanceThreshold').evaluate(el=>{el.value='0';el.dispatchEvent(new Event('input',{bubbles:true}));});if(await page.locator('#thresholdValue').textContent()!=='0%')throw Error('Salience threshold control failed');const allResults=await page.locator('.result-item').count();if(allResults<=defaultResults)throw Error('Lower threshold should reveal substantially more results');
 const opacities=await page.locator('.mark').evaluateAll(els=>[...new Set(els.map(el=>el.style.getPropertyValue('--mark-opacity')))]);if(opacities.length<2)throw Error('Highlight intensity is not continuous');
 const merged=await page.evaluate(()=>eval("mergeNearbyEvidence([{id:'a',page:1,paragraphId:'p',text:'A',rects:[[.1,.1,.3,.02]],kind:'sentence'},{id:'b',page:1,paragraphId:'p',text:'B',rects:[[.1,.13,.3,.02]],kind:'sentence'}]).length"));if(merged!==1)throw Error('Nearby evidence was not merged');
 if(await page.locator('.paragraph-frame').count())throw Error('Paragraph outline should not be rendered');
 const highlightColor=await page.locator('.mark').first().evaluate(el=>getComputedStyle(el).backgroundColor);if(!highlightColor.includes('255'))throw Error('Highlights are not yellow');
 if(!await page.locator('.figure-frame').count())throw Error('No caption-linked figure frame');
 const figureStyle=await page.locator('.figure-frame').first().evaluate(el=>{const s=getComputedStyle(el);return {background:s.backgroundColor,outlineColor:s.outlineColor,outlineStyle:s.outlineStyle,outlineWidth:parseFloat(s.outlineWidth),outlineOffset:parseFloat(s.outlineOffset),evidenceId:el.dataset.evidenceId};});
 if(figureStyle.background!=='rgba(0, 0, 0, 0)')throw Error('Figure should not use a filled highlight');
 if(figureStyle.outlineStyle!=='dashed'||figureStyle.outlineWidth<3||figureStyle.outlineOffset<4)throw Error('Figure should use a thick outward dashed frame');
 if(figureStyle.outlineColor!=='rgb(255, 210, 48)')throw Error('Figure frame should use bright highlight yellow');
 if(await page.locator(`.result-item[data-id="${figureStyle.evidenceId}"]`).count()!==1)throw Error('Figure and caption should be one result');
 if(await page.locator(`.mark[data-evidence-id="${figureStyle.evidenceId}"]:not(.figure-frame)`).count()<1)throw Error('Figure caption should share the figure evidence and keep text highlighting');
 const figureBoost=await page.evaluate(()=>eval("(()=>{const saved=activeQuestion;activeQuestion='What does Figure 1 show?';const boosted=priorityScoreOf({score:2,kind:'figure'})>priorityScoreOf({score:2,kind:'sentence'});activeQuestion=saved;return boosted})()"));if(!figureBoost)throw Error('Figure priority boost failed');
 await page.locator('.figure-frame').first().click();
 if(!await page.locator('.figure-frame.focused').count())throw Error('Figure navigation failed');
 await page.waitForFunction(()=>{const img=document.querySelector('#page-3 img');return img?.complete && img.naturalWidth>0;});
 await page.screenshot({path:path.join(__dirname,'figure-mocked.png')});
 await page.locator('#relevanceThreshold').evaluate(el=>{el.value='50';el.dispatchEvent(new Event('input',{bubbles:true}));});
 await page.locator('.result-item').first().click();if(!await page.locator('.mark.focused').count())throw Error('Focus failed');
 await page.screenshot({path:path.join(__dirname,'highlights-mocked.png')});
 await page.locator('#resultSort').selectOption('document');const orderedPages=(await page.locator('.result-item .result-meta span:last-child').allTextContents()).map(x=>Number(x.match(/\d+/)?.[0]));if(orderedPages.some((x,i)=>i&&x<orderedPages[i-1]))throw Error('Document order sorting failed');
 await page.locator('#resultSort').selectOption('relevance');
 await page.locator('#highlightToggle').click();if(!await page.locator('#pages.highlights-off').count())throw Error('Toggle failed');
 await page.locator('#history summary').click();await page.locator('#historyItems button').click();if(await page.locator('#question').inputValue()!=='How was the experiment designed?')throw Error('History failed');
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(__dirname,'mobile.png')});
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);if(overflow)throw Error('Mobile horizontal overflow');
 if(errors.length)throw Error(errors.join('\n'));console.log('PASS: upload, pause control, mocked scoring, merged evidence, both sorts, highlights, navigation, history, mobile layout; no live API requests.');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
